version: '3.2'

services:
    php:
        build:
            context: .
            dockerfile: config/docker/php/Dockerfile.dev
            args:
                - HOST_UID=${HOST_UID}
                - HOST_GUID=${HOST_GUID}
        volumes:
            - .:/var/www/html
            - ${HOST_COMPOSER_HOME}:/var/www/html/var/.composer
        environment:
            - COMPOSER_HOME=/var/www/html/var/.composer
    nginx:
        build:
            context: .
            dockerfile: config/docker/nginx/Dockerfile.dev
            args:
                - HOST_UID=${HOST_UID}
                - HOST_GUID=${HOST_GUID}
        depends_on:
            - php
        ports:
            - ${EXTERNAL_HTTP_PORT}:80
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
        environment:
            - UPSTREAM=php:9000