FROM php:7.3-fpm-alpine

WORKDIR /var/www/html

RUN apk add --no-cache \
    git \
    icu-dev \
    libzip-dev \
    && docker-php-ext-install \
        intl \
        opcache \
        zip \
    && apk add --no-cache --virtual .phpize ${PHPIZE_DEPS} \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del .phpize

COPY --from=composer /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_MEMORY_LIMIT=-1

ARG HOST_UID=1000
ARG HOST_GUID=1000

RUN deluser www-data \
    && addgroup -g "${HOST_GUID}" www-data \
    && adduser -u "${HOST_UID}" -G www-data -H -s /bin/sh -D www-data

ENV XDEBUG_ENABLED=false

COPY config/docker/php/entrypoint.dev.sh /usr/bin/entrypoint
COPY config/docker/php/xdebug.ini /usr/local/etc/php/xdebug.ini

RUN cat /usr/local/etc/php/xdebug.ini >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && chmod +x /usr/bin/entrypoint

ENTRYPOINT ["/usr/bin/entrypoint"]
